"""rbac roles system

Revision ID: 707f52f0a927
Revises: 587a573a8257
Create Date: 2026-02-27 15:16:12.963269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707f52f0a927'
down_revision = '587a573a8257'
branch_labels = None
depends_on = None


def upgrade():
    # 1️⃣ Create role table
    op.create_table(
        'role',
        sa.Column('role_id', sa.BigInteger(), primary_key=True),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('location_id', sa.BigInteger(), nullable=False),
        sa.Column('is_system', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('created_by', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['location_id'], ['location.loc_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['created_by'], ['app_user.user_id'])
    )

    # 2️⃣ Add role_id as NULLABLE first
    op.add_column('employment',
        sa.Column('role_id', sa.BigInteger(), nullable=True)
    )

    op.create_foreign_key(
        None,
        'employment',
        'role',
        ['role_id'],
        ['role_id']
    )

    # 3️⃣ Create default roles per location
    op.execute("""
        INSERT INTO role (name, location_id, is_system)
        SELECT 'Owner', loc_id, TRUE FROM location;

        INSERT INTO role (name, location_id, is_system)
        SELECT 'Manager', loc_id, TRUE FROM location;

        INSERT INTO role (name, location_id, is_system)
        SELECT 'Staff', loc_id, TRUE FROM location;
    """)

    # 4️⃣ Migrate old position → role_id
    op.execute("""
        UPDATE employment e
        SET role_id = r.role_id
        FROM role r
        WHERE LOWER(e.position) = LOWER(r.name)
        AND e.location_id = r.location_id;
    """)

    # 5️⃣ Now enforce NOT NULL
    op.alter_column('employment', 'role_id', nullable=False)

    # 6️⃣ Drop old column
    op.drop_column('employment', 'position')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_employment_role_id_role'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_employment_role_id'))
        batch_op.drop_column('role_id')

    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_location_id'))

    op.drop_table('role')
    # ### end Alembic commands ###
