"""v2 shift swap notification plan

Revision ID: 72c06bf95b33
Revises: 707f52f0a927
Create Date: 2026-05-13 13:33:58.612296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72c06bf95b33'
down_revision = '707f52f0a927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_token', sa.Text(), nullable=True))
        # ✅ Fixed: existing rows get NOW() as default
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False,
                                      server_default=sa.text('NOW()')))
        batch_op.drop_column('is_active')

    with op.batch_alter_table('company', schema=None) as batch_op:
        # ✅ Fixed: existing companies default to 'free' plan
        batch_op.add_column(sa.Column('plan', sa.Text(), nullable=False,
                                      server_default=sa.text("'free'")))
        batch_op.add_column(sa.Column('plan_expires', sa.DateTime(), nullable=True))

    with op.batch_alter_table('employment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ux_employment_user_comp_loc'), type_='unique')
        batch_op.create_index(batch_op.f('ix_employment_role_id'), ['role_id'], unique=False)

    with op.batch_alter_table('location', schema=None) as batch_op:
        # ✅ Fixed: existing locations default to UTC
        batch_op.add_column(sa.Column('timezone', sa.Text(), nullable=False,
                                      server_default=sa.text("'UTC'")))

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_location_id'), ['location_id'], unique=False)
        batch_op.create_unique_constraint('uq_role_name_location', ['name', 'location_id'])

    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.BigInteger(), nullable=True))
        # ✅ Fixed: existing shifts default to 0 break minutes
        batch_op.add_column(sa.Column('break_minutes', sa.Integer(), nullable=False,
                                      server_default=sa.text('0')))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        # ✅ Fixed: existing shifts were not AI created
        batch_op.add_column(sa.Column('created_by_ai', sa.Boolean(), nullable=False,
                                      server_default=sa.text('false')))
        batch_op.add_column(sa.Column('created_by', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))
        # ✅ Fixed: existing shifts get NOW() as created_at
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False,
                                      server_default=sa.text('NOW()')))
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_shift_role_id_role'), 'role', ['role_id'], ['role_id'])
        batch_op.create_foreign_key(batch_op.f('fk_shift_created_by_app_user'), 'app_user', ['created_by'], ['user_id'])

    with op.batch_alter_table('shift_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_by', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_shift_assignment_assigned_by_app_user'), 'app_user', ['assigned_by'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_shift_assignment_assigned_by_app_user'), type_='foreignkey')
        batch_op.drop_column('assigned_by')

    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_shift_created_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_shift_role_id_role'), type_='foreignkey')
        batch_op.alter_column('end_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('published_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('created_by_ai')
        batch_op.drop_column('notes')
        batch_op.drop_column('break_minutes')
        batch_op.drop_column('role_id')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint('uq_role_name_location', type_='unique')
        batch_op.drop_index(batch_op.f('ix_role_location_id'))

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    with op.batch_alter_table('employment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employment_role_id'))
        batch_op.create_unique_constraint(batch_op.f('ux_employment_user_comp_loc'), ['user_id', 'comp_id', 'location_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('plan_expires')
        batch_op.drop_column('plan')

    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('push_token')

    # ### end Alembic commands ###