"""add clock settings and break entry

Revision ID: b42f3b726200
Revises: 72c06bf95b33
Create Date: 2026-05-14 17:00:44.687394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42f3b726200'
down_revision = '72c06bf95b33'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clock_in_method', sa.Text(), nullable=False,
            server_default=sa.text("'gps'")))
        batch_op.add_column(sa.Column('break_duration_mins', sa.Integer(), nullable=False,
            server_default=sa.text('30')))
        batch_op.add_column(sa.Column('max_breaks_per_shift', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('paid_break', sa.Boolean(), nullable=False,
            server_default=sa.text('false')))
        batch_op.add_column(sa.Column('gps_radius_meters', sa.Integer(), nullable=False,
            server_default=sa.text('100')))
        batch_op.add_column(sa.Column('clock_in_pin', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pin_generated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('time_entry', schema=None) as batch_op:
        batch_op.drop_column('break_minutes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('break_minutes', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('pin_generated_at')
        batch_op.drop_column('clock_in_pin')
        batch_op.drop_column('gps_radius_meters')
        batch_op.drop_column('paid_break')
        batch_op.drop_column('max_breaks_per_shift')
        batch_op.drop_column('break_duration_mins')
        batch_op.drop_column('clock_in_method')

    # ### end Alembic commands ###
