"""add employee profile fields

Revision ID: d1126c781da6
Revises: b42f3b726200
Create Date: 2026-05-17 12:08:31.499781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1126c781da6'
down_revision = 'b42f3b726200'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('employment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hourly_rate', sa.Numeric(10, 2), nullable=True))
        batch_op.add_column(sa.Column('employment_type', sa.Text(), nullable=False,
            server_default=sa.text("'full_time'")))
        batch_op.add_column(sa.Column('max_hours_week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('overtime_eligible', sa.Boolean(), nullable=False,
            server_default=sa.text('true')))
        batch_op.add_column(sa.Column('phone', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('emergency_phone', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employment', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('emergency_phone')
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('phone')
        batch_op.drop_column('overtime_eligible')
        batch_op.drop_column('max_hours_week')
        batch_op.drop_column('employment_type')
        batch_op.drop_column('hourly_rate')

    # ### end Alembic commands ###
